### ISSUE TITLE
Crosshairs don't move with the series when the chart is scrolled (gh-pages main demo chart)

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3-financial-components#116]
If the crosshairs are frozen at a particular point, and the chart is scrolled left or right, the crosshairs will not move with the series:

![crosshairs](https://cloud.githubusercontent.com/assets/2017615/5340172/4fed1256-7ee1-11e4-9ca5-7604dded7544.PNG)

**Comment by andyaiken** [comment]
Fixed in #183
