### ISSUE TITLE
Develop a build / release process

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3-financial-components#124]
We need a documented / semi-automated process that details the following:

+ When a release is made, we need to update version numbers everywhere they appear (`package.json`, `fc.js`, website)
+ When releasing, we need to ensure that the `dist` folder contains the built code, and that the website also uses this same code.
+ The repo needs to be tagged
+ Build the components JSDocs (as per #136) and add to the website
+ (optionally) create a [github release](https://github.com/blog/1547-release-your-software)

**Comment by chrisprice** [comment]
Done
