### ISSUE TITLE
Removed hard-coded 'date' properties

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3-financial-components#130]
Similar to #105 - the `date` property is hard-coded for a number of the components.

**Comment by chrisprice** [comment]
#244 #245 should fix the remaining tools.

**Comment by chrisprice** [comment]
* [ ] Bollinger Bands

**Comment by chrisprice** [comment]
Just needs the following removing from point snap -
```
xValue = series.xValue ? series.xValue() : function(d) { return d.date; },
```

**Comment by chrisprice** [comment]
Removed in #349
