### ISSUE TITLE
Standardise the CSS

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3-financial-components#131]
CSS should be dash formatted, e.g. `moving-average`, not camel case, `movingAverage`.
CSS classes should be added via the component, not the user's calling code.

TODO:

 - [x] indicators
 - [x] series
 - [x] scale
 - [x] tools
 - [x] utilities

**Comment by chrisprice** [comment]
While not completely consistent, it's a lot better than it was.
