### ISSUE TITLE
We need a better mechanism for testing components

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3-financial-components#145]
I'm not sure how everyone else is doing it, but I have my own test pages. We could do with a visual test of some sort that allows us to rapidly inspect the various components and test their basic functionality.

**Comment by jleft** [comment]
> @jleft can you also add test cases for ordinal scales? Some components almost work, e.g. line series. Whereas others, e.g. bar, ohlc, candlestick, have dateTime axis concepts backed in.

Sure, no problem.

---

An initial test page and a few tests can be seen here: https://github.com/jleft/d3-financial-components/commit/fda786a48a47ef3150d504f739ccd5b1603116f4

There's a single HTML page with all of the test cases; each test case has its own `div` and JS file.
