### ISSUE TITLE
DateTime axis issues with zoom

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3-financial-components#180]
Comments from PR https://github.com/ScottLogic/d3-financial-components/pull/175#issuecomment-67402649

Some things I found when using this with zoom (see http://bl.ocks.org/tlsim/0ffc31b5cd4d7560148e)

+ Tick positions jump on first zoom redraw.
+ There's a gap at the start depending on the start day with hideWeekends(true)
+ Weekend days are mapped to the same values as Monday/Tuesday, so maybe change the name to moveWeekends or similar?

**Comment by tunerscafe** [comment]
As far as I'm aware these are all resolved now, apart from the renamed function.

**Comment by ColinEberhardt** [comment]
@tlsim as you raised these points initially, I'd like to have your view as to whether they are resolved?

**Comment by tlsim** [comment]
I updated the example to use dist files built from the current master, and the issues with the scale are still there. http://bl.ocks.org/tlsim/0ffc31b5cd4d7560148e

**Comment by chrisprice** [comment]
Assume this is fixed, as the scale has been redone.
