### ISSUE TITLE
Date Time scale 'padEnds()' function has no affect

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3-financial-components#204]
Setting `padEnds()` to true, when using the `dateTime` scale has no affect at all, for example:

```js
var dateScale = fc.scale.dateTime()
    .domain([dateFrom, dateTo])
    .range([0, chartLayout.getPlotAreaWidth()])
    .padEnds(true)
    .nice();
```

**Comment by tunerscafe** [comment]
The order of the calls is important. padEnds and/or hideWeekends need to be called before the domain is set.

**Comment by jleft** [comment]
I've tried calling padEnds before setting the domain and the charts still look identical, see these examples [with](http://bl.ocks.org/jleft/a7ce1ecc5df5c208f5e5) and [without](http://bl.ocks.org/jleft/243c4b57ff738308335d) padEnds.

**Comment by tunerscafe** [comment]
Looking at the code it turns out that padEnds does nothing... will need to look through histiry to see where it went?

**Comment by chrisprice** [comment]
Still a problem @jleft ?
