### ISSUE TITLE
Move pixel alignment functionality to the top level

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3-financial-components#206]
Currently the scales have an option (default enabled) to produce "pixel-rounded values" (i.e. to the nearest x.5). However, there's no equivalent for non-scaled elements e.g. axes.

An alternative approach would be to have a top level offset (0.5, 0.5) optionally applied by the chart layout to chartArea. The scales would then optionally produce integer-rounded values.

**Comment by tunerscafe** [comment]
:+1: Tested on my test pages and works a treat.
