### ISSUE TITLE
OHLC has three render modes, keep? or simplify?

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3-financial-components#210]
Currently the OHLC series has three different methods that can be used to render the series, each one having a different performance characteristic.

Do we want to keep this feature or not?

If we do keep it, we need to make it more obvious what this feature does. By choosing the more high-performance version I presume you sacrifice some functionality?

Ideally I'd like to see an equivalent visitor function as per #202

**Comment by tunerscafe** [comment]
If we don't sacrifice any functionality in the higher performance mode, then it makes no sense to keep all three.

**Comment by chrisprice** [comment]
Agreed, not sure if there's a difference when it comes to styling?
