### ISSUE TITLE
Add data points to the line series

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3-financial-components#211]
Currently the line series can render a line, or a filled area. It could be easily extended to render 'points' at each datapoint location:

![image](https://cloud.githubusercontent.com/assets/1098110/5626192/efe23340-957f-11e4-8128-b4d6727d0ea4.png)

**Comment by chrisprice** [comment]
We now have a point series, do we still want to add this?

**Comment by ColinEberhardt** [comment]
No, having a separate point series will do just fine :-)
