### ISSUE TITLE
Annotation tool generates elements with duplicate (non-unique) IDs

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3-financial-components#223]
Unless an [annotation's `index`](https://github.com/ScottLogic/d3-financial-components/blob/67a49925df10007a31ea5b692e4c66e1c4bf2fba/components/tools/annotation.js#L6) is explicitly set, multiple instances of the component will generate elements with the same ID:

![annotation-ids](https://cloud.githubusercontent.com/assets/2017615/5662003/b7e66a68-972a-11e4-9a90-2038d441d735.PNG)

I think the component's default behavior should avoid this issue, similar to the clipping path's ID in chart layout.

I'm not sure if a default ID is necessary at all? If not, then the simplest solution would be to remove it.

Otherwise, I'd suggest allowing the user the explicitly set an ID for the element (it's their responsibility to ensure it's unique), but if the ID isn't explicitly set, then the index should be incremented (in a similar way to [chartLayout](https://github.com/ScottLogic/d3-financial-components/blob/67a49925df10007a31ea5b692e4c66e1c4bf2fba/components/utilities/chartLayout.js#L455)).

Thoughts?

**Comment by chrisprice** [comment]
Do we have an example use case for the id? If not I'd be happy to see it
removed.

**Comment by jleft** [comment]
If the user wants multiple annotations - [like in the example app](http://scottlogic.github.io/d3-financial-components/app/index.html) - then this could be useful, so the appropriate elements can be easily selected and updated.

However, I'm not sure which would be better - encapsulating the ID functionality into the component, or leaving it as the user's responsibility.

**Comment by chrisprice** [comment]
Decorate to the rescue again?

**Comment by jleft** [comment]
Yeah, that'd work!

**Comment by chrisprice** [comment]
I'd hold off any work on this until #230 is resolved.
