### ISSUE TITLE
Annotation tool label text formatting could be more flexible

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3-financial-components#225]
The annotation's label text [follows the following format](https://github.com/ScottLogic/d3-financial-components/blob/67a49925df10007a31ea5b692e4c66e1c4bf2fba/components/tools/annotation.js#L37):

```js
.text(yLabel + ': ' + formatCallout(yValue))
```

This is fairly restrictive and, at least, forces the label to contain a colon, followed by a space.

This could be simplified (which will also make the `yLabel` property redundant):

```js
.text(formatCallout(yValue))
```

This affords more flexibility to the label formatting; any additional text can still be added relatively easily to the label, for example:

```js
var annotation101 = fc.tools.annotation()
    .xScale(dateScale)
    .yScale(priceScale)
    .yValue(101)
    .formatCallout(function(d) { return 'Some text: ' + d3.format('.1f')(d); });
```

**Comment by chrisprice** [comment]
Agreed, I think this change could be made to many components. Should we
standardise on label (I.e. formatLabel(d)) as the naming convention? Or are
there cases where label doesn't make sense (works for crosshairs which is
the example I'm thinking of)?

**Comment by jleft** [comment]
> Should we standardise on label (I.e. formatLabel(d)) as the naming convention?

Sounds good to me - I think label makes sense.

+ Crosshairs and measure have 'horizontal' and 'vertical' labels
+ Annotation has a single label
+ Callouts is a bit odd - the label is added to 'data' rather than as a property of the component - but, as far as the naming convention is concerned, label still seems to fit

**Comment by chrisprice** [comment]
I'd hold off any work on this until #230 is resolved.
