### ISSUE TITLE
fc.utilities.extent add optional padding?

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3-financial-components#228]
When constructing an ordinal scale, you have the option of adding padding:

https://github.com/mbostock/d3/wiki/Ordinal-Scales#ordinal_rangeRoundBands

It would be useful to add a similar concept to our extent function.

**Comment by tunerscafe** [comment]
Having looked at this for @jleft in the past, it would appear that the function does nothing. So it will need implementing on both.

**Comment by ColinEberhardt** [comment]
> Having looked at this for @jleft in the past, it would appear that the function does nothing. So it will need implementing on both.

Not sure what you mean? I was just thinking of adding a padding parameter to our own extent function,

**Comment by tunerscafe** [comment]
The dateScale  component has a padEnds property that currently does nothing. I noticed it when @jleft was having problems using it.

**Comment by jleft** [comment]
#204 has more information on the padEnds issue.

I think adding this functionality to extent, so it will be compatible with multiple scales without duplication, is a good idea.

**Comment by chrisprice** [comment]
When we had wrapped up dateScale this was a bigger problem than it is now. As it stands ```scale.nice()``` seems to be handling the issues we were previously seeing. In the edge case that it doesn't handle it nicely, manually padding the returned values isn't a big deal.
