### ISSUE TITLE
visual tests/index.html contains a local link to livereload script on localhost

### ISSUE THREAD

**Issue by tunerscafe** [ScottLogic/d3-financial-components#231]

**Comment by chrisprice** [comment]
That's intentional, is it causing you an issue?

**Comment by jleft** [comment]
I don't think this is a bug; it's required to use [livereload](https://github.com/gruntjs/grunt-contrib-watch#optionslivereload) in the [Grunt Watch task](https://github.com/ScottLogic/d3-financial-components/blob/576f0b25c1ca47081683f856877c284272c1c2cf/Gruntfile.js#L74). When running Grunt watch, a livereload server is started and the page refreshes automatically when a source file is modified:

**Comment by tunerscafe** [comment]
Ah OK, my mistake, it was just the port number I assumed would be different on very machine.
