### ISSUE TITLE
Roll out the simplified approach to exposing properties

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3-financial-components#232]
As introduced here: https://github.com/ScottLogic/d3-financial-components/pull/229/files#diff-a30185c4c94d14d4cf8dabce084e834fR6

**Comment by jleft** [comment]
#### Indicators
 + [ ] Bollinger Bands
 + [ ] Moving Avergage
 + [ ] RSI

#### Scale
 + [ ] Date Time
 + [ ] Linear
 + [ ] Gridlines

#### Series
 + [ ] Bar
 + [ ] Candlestick
 + [ ] Comparison
 + [ ] Line
 + [ ] OHLC

#### Tools
 + [ ] Annotation
 + [ ] Callouts
 + [ ] Crosshairs
 + [ ] Fibonacci Fan
 + [ ] Measure

#### Utilities
 + [ ] Chart Builder
 + [ ] Chart Layout
 + [ ] Data Generator

**Comment by chrisprice** [comment]
#244 #245 should fix fan and measure

**Comment by chrisprice** [comment]
This has been superseded by #275
