### ISSUE TITLE
fc.scales.dateTime with hideWeekends(true) adds excessive padding

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3-financial-components#241]
See the crosshairs examples in PR #207.

**Comment by chrisprice** [comment]
@ColinEberhardt just went to check if this was still an issue and it looks like there's a random label floating to the left of the axis now. Also there's no padding what-so-ever... think something's gone wrong...

**Comment by ColinEberhardt** [comment]
Thanks for checking, I've self-assigned, and will take a look

**Comment by ColinEberhardt** [comment]
Found the issue, the values returned by the `ticks` function may fall within discontinuities. I'll sort this out ...

**Comment by ColinEberhardt** [comment]
The same is probably true of `nice`, which can change the domain.

**Comment by chrisprice** [comment]
PR replaces issue
