### ISSUE TITLE
Support locking the tools to data points not just pixel points

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3-financial-components#246]
Currently the tools share a common mechanism for snapping which only supports returning pixel values to the tools. This means that if the axes' scales are changed then the tool will not automatically move itself with the data.

We should extend the snapping behaviour to allow optionally returning data values instead of pixel values. The tools should then transform these data values into pixel values on each ```.call(tool)```.

**Comment by ColinEberhardt** [comment]
On a related note, if a snapping function is not provided, the crosshair only supplies the screen coordinates to the formatting function. In this context it should probably provide domain coordinates.
