### ISSUE TITLE
Standardise the SVG element structure

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3-financial-components#255]
We should either -
* Always have a root element appended to the selection by the component to which all other in the component. This root element will have a CSS class and all CSS will use a descendant selector on that class name.
* Never add a root element. All CSS should target CSS classes as appropriate.

**Comment by chrisprice** [comment]
Having worked with the components as part of the bollinger bands refactoring I'm strongly for not adding root elements.

**Comment by jleft** [comment]
> Having worked with the components as part of the bollinger bands refactoring I'm strongly for not adding root elements.

:+1: I agree, I've found this to be the most appropriate solution. For what it's worth, D3's axis component does the same thing.
