### ISSUE TITLE
Should there be an implicit opacity transforms on simpleDataJoin'ed components?

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3-financial-components#259]
I.e. In this [PR](https://github.com/ScottLogic/d3-financial-components/pull/242/files) should the opacity code have been moved from bar.js to simpleDataJoin.js?

**Comment by jleft** [comment]
I don't have a strong opinion at the moment, but I definitely think it's worth considering and discussing further.

**Comment by chrisprice** [comment]
Yes it should be moved is the decision
