### ISSUE TITLE
D3 node module dependencies

### ISSUE THREAD

**Issue by tlsim** [ScottLogic/d3-financial-components#280]
#262 added D3 to the package.json - this brings in contextify (via JSDOM) as a dependency. Building this with node-gyp requires Python, Make and a C/C++ compiler on unix, and Visual Studio C++ on Windows.

Installing contextify with npm fails for me on OS X 10.10.2 with Python and the XCode command line tools installed:

> node-gyp rebuild
make: *** No rule to make target `../../../../../../../../../Volumes/Macintosh', needed by `Makefile'.  Stop.
gyp ERR! build error
...
gyp ERR! not ok 

It seems we're only doing this to have d3.js in the visual tests. Could we instead get it from http://d3js.org and download if needing it offline?

**Comment by ColinEberhardt** [comment]
Ah, didn't realise d3 dragged all that complexity along with it. I'd be happy to revert this.

**Comment by chrisprice** [comment]
Works fine for me on the same versions, have you tried updating node?

I agree it's a PITA on windows though and we should do something about it. However, I do like the offline-ability of it, I do a lot of work on this project while I commute. As d3 seem to be removing it in the [next version](https://github.com/mbostock/d3/issues/2190) could we move it to the optional dependencies list as a workaround for now?

**Comment by jleft** [comment]
I think changing D3 to an optional dependency would make sense - npm will continue if the dependency cannot be installed.  We could add a check to the visual test's HTML and the Gruntfile (for Jasmine) to load from http://d3js.org, if the local version isn't available.

Bower only brings in the essentials, so would work too.

**Comment by chrisprice** [comment]
We could just make them load both?

I have a strong preference for not using bower for this: we're building a
library rather than pulling in libraries to make an app.

**Comment by jleft** [comment]
> We could just make them load both?

Yeah, that'd work too.

> I have a strong preference for not using bower for this: we're building a
library rather than pulling in libraries to make an app.

I was thinking that the visual tests are an 'app' of sorts, but I see you point.

---

I'm happy to make this change, changing D3 to an optional dependency, if that's agreeable?

**Comment by mbostock** [comment]
FWIW, I’m demoting JSDOM to a development dependency (only used for D3’s tests). That in turn should remove JSDOM’s contextify dependency, which complicates the build. See mbostock/d3#2225.

**Comment by chrisprice** [comment]
Thanks @mbostock! Version 3.5.4 contains the fix, we should upgrade to that ASAP.

https://www.npmjs.com/package/d3
