### ISSUE TITLE
How to Update Chart on New Data?

### ISSUE THREAD

**Issue by joncursi** [ScottLogic/d3-financial-components#298]
Great work so far on this D3 sub-library, I'm enjoying working with it!

Question - how do you guys recommend updating the charts when new data becomes available on the client, without having to destroy the existing chart and re-drawing it from scratch? The base series data would beed to be patched and/or shifted, and the same for any indicators/overlays/annotations currently present on the chart. Thanks!

**Comment by chrisprice** [comment]
The d3 idiom is normally to re-run the code you used to generate the chart in the first place. The data-join concept should mean that only the changed values are actually updated. [This article](http://bost.ocks.org/mike/join/) covers the concept in more detail.

In the current version we've wrapped that up in ```simpleDataJoin``` but it's just a very thin wrapper.

**Comment by jleft** [comment]
An example of this is the [bar transition visual test](https://github.com/jleft/d3-financial-components/blob/03f17b5468074de55b5cf828fd39c4a033ed1718/visual-tests/test-scripts/series/bar-transitions.js#L91); when the data is changed, the scales' domains are updated and the components (axis and bar series in this case), which follow the [general update pattern](http://bl.ocks.org/mbostock/3808218), are called again on their corresponding selection.
