### ISSUE TITLE
Height of bars in bar series is not calculated correctly

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3-financial-components#300]
For example, see the [static bar series visual test](https://github.com/ScottLogic/d3-financial-components/blob/b58727104458eb550b2071ebdb92055bcc5f170c/visual-tests/src/test-fixtures/series/bar.js):

![bar-height](https://cloud.githubusercontent.com/assets/2017615/7121086/d44b3f1a-e209-11e4-8a76-e1229898d299.PNG)

**Comment by jleft** [comment]
The height of the bar is calculated as `y(0) - y(d)`, which is reasonable; it looked odd to me in the example above as the minimum domain value was significantly higher than 0.

#314 is likely going to introduce a configurable y0/baseline property, which will solve this issue, once it's merged, this can be closed.

**Comment by chrisprice** [comment]
#314 is merged, assume this is now fixed.
