### ISSUE TITLE
Refactor utilities.pointSnap to work with ordinal scales.

### ISSUE THREAD

**Issue by janakerman** [ScottLogic/d3-financial-components#301]
Currently, utilities.pointSnap uses the method `invert` to calculate the data value from the pixel position. This method is only available on quantitative series, meaning we can't use it for crosshairs on ordinal series. 

Being able to use this would greatly simplify use cases where crosshairs and ordinal scales are required. The `stacked-bar.js` visual test is a great example of this.

**Comment by chrisprice** [comment]
Good spot, do you have a feel for what kind of changes would be required?

**Comment by janakerman** [comment]
I don't think this would be a large change. From the Quantitative [invert](https://github.com/mbostock/d3/wiki/Quantitative-Scales) method:
> Returns the value in the input domain x for the corresponding value in the output range y.

So, for our use case, given pixel it gives us a data value. The Ordinal scale doesn't have this method as it is arguable as to whether it makes sense that you can interpolate between ordinal values. We'd need to assess the logic we are using to do this in `stacked-bar.js`, and potentially write a shim adding an `invert` implementation for Ordinal series.

**Comment by chrisprice** [comment]
Would it makes sense to have a point snap utility specifically for ordinal
scales?

I agree that invert doesn't really mean anything in the general case for an
ordinal scale so I'm not sure how useful a generic polyfil would be.

**Comment by chrisprice** [comment]
Sorry shim

**Comment by janakerman** [comment]
Yeah, I think there's an argument to be made for that. Although the `pointSnap` handles the snapping behaviour for both axes so may need to split the crosshair's snapping algorithm up into a snapping algorithm per-axis, as we may have any combination of axes (quantitative, time and ordinal).
