### ISSUE TITLE
Failing unit test as of origin/master (45026a)

### ISSUE THREAD

**Issue by janakerman** [ScottLogic/d3-financial-components#312]
The following unit test is failing:

     layout
       ...
       X should permit layout with an explicit width / height

The failing test seems to have been introduced by the commit `82a6bf`.

**Comment by jleft** [comment]
The Travis build passed - are your `node_modules` up to date?

**Comment by janakerman** [comment]
I'll check. I hadn't looked into why it was failing just yet - I just wanted to raise it before I forgot about it!

**Comment by jleft** [comment]
Yeah, always a good idea to raise these issues :) Out of date dependencies has caught me out a few times before, so is always worth checking!

**Comment by janakerman** [comment]
The tests run fine after updating my `node_modules`. I'll remember that for the future. Thanks for the tip!
