### ISSUE TITLE
Make xValue accessor more flexible

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3-financial-components#316]
The xValue function used by point series (and others) should be changed to supply both the current datapoint and the index to the accessor function:

https://github.com/ScottLogic/d3-financial-components/blob/master/components/series/point.js#L7

Changing from this:

    var x = function(d) { return point.xScale.value(point.xValue.value(d)); };

To something like this:

    var x = function(d, i) { return point.xScale.value(point.xValue.value(d, i)); };

This would allow you to use the series with data where the x-value is based on the order within the data array

**Comment by chrisprice** [comment]
Fixed by #347 for all series value accessors
