### ISSUE TITLE
Remove JSDoc?

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3-financial-components#330]
As we're no longer using JSDoc documentation comments, perhaps it's worth removing any remaining comments/checking they're not obsolete, removing the dev dependency and associated Grunt task(s)? It may be confusing for a new user to have partial JSDoc documentation.

**Comment by ColinEberhardt** [comment]
I'm in two minds abuout this one, I know we don't plan to generate and publish the jsdoc, but it does provide a recognised structure of you do feel the need to document the input params for a function (as an example).

**Comment by chrisprice** [comment]
Let's stick with it in the code where we think it's appropriate but get rid of the grunt stuff.
