### ISSUE TITLE
If the scale domain depends on the indicator algorithm - we are in trouble

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3-financial-components#371]
On the current website the bollinger upper / lower bands fall outside of the y axis domain. Unfortunately, because the bollinger algorithm is executed within the bollinger series, there is no way to set the y domain to a suitable value before rendering.

This is an even bigger issue for indicators such as macd.

**Comment by chrisprice** [comment]
@ColinEberhardt is this still an issue?

**Comment by ColinEberhardt** [comment]
No :-)
