### ISSUE TITLE
small typo in example site

### ISSUE THREAD

**Issue by eesur** [ScottLogic/d3-financial-components#375]
in [line series example](http://scottlogic.github.io/d3-financial-components/components.html#line) refers to 'point' both in the code and description (instead of 'line'). Also in bar series code below, it has `var point` (instead of `var bar`)

**Comment by ColinEberhardt** [comment]
Thanks for spotting these typos - I'll fix them shortly :-)

**Comment by jleft** [comment]
Fixed in #380 - please reopen if you disagree.
